# Generated by Django 6.0.6 on 2026-06-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='description',
        ),
    ]
