# Generated by Django 6.0.6 on 2026-06-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0002_rename_name_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
