# Generated by Django 6.0.6 on 2026-06-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0003_alter_todo_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
