# Generated by Django 6.0.6 on 2026-06-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0007_alter_todo_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
