# Generated by Django 6.0.6 on 2026-06-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0008_remove_customuser_address_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
