# Generated by Django 6.0.6 on 2026-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0011_alter_customuser_email_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
