# Generated by Django 6.0.6 on 2026-07-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0012_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='final_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
